packages:
  - apps/*
  - packages/*
  - packages/modules/*
  - packages/adapters/*

peerDependencyRules:
  ignoreMissing:
    - monaco-editor
    - yjs

onlyBuiltDependencies:
  - esbuild
  - sharp
  - unrs-resolver
  - workerd
