/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    groups: Group;
    organizations: Organization;
    projects: Project;
    tasks: Task;
    workflows: Workflow;
    activity: Activity;
    attachments: Attachment;
    notifications: Notification;
    emailMessages: EmailMessage;
    jobRuns: JobRun;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    groups: GroupsSelect<false> | GroupsSelect<true>;
    organizations: OrganizationsSelect<false> | OrganizationsSelect<true>;
    projects: ProjectsSelect<false> | ProjectsSelect<true>;
    tasks: TasksSelect<false> | TasksSelect<true>;
    workflows: WorkflowsSelect<false> | WorkflowsSelect<true>;
    activity: ActivitySelect<false> | ActivitySelect<true>;
    attachments: AttachmentsSelect<false> | AttachmentsSelect<true>;
    notifications: NotificationsSelect<false> | NotificationsSelect<true>;
    emailMessages: EmailMessagesSelect<false> | EmailMessagesSelect<true>;
    jobRuns: JobRunsSelect<false> | JobRunsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: string;
  };
  fallbackLocale: null;
  globals: {
    settings: Setting;
  };
  globalsSelect: {
    settings: SettingsSelect<false> | SettingsSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: string;
  name: string;
  role: 'owner' | 'manager' | 'staff';
  active?: boolean | null;
  groups?: (string | Group)[] | null;
  reportsTo?: (string | null) | User;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "groups".
 */
export interface Group {
  id: string;
  name: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "organizations".
 */
export interface Organization {
  id: string;
  name: string;
  website?: string | null;
  phone?: string | null;
  email?: string | null;
  owner?: (string | null) | User;
  customData?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects".
 */
export interface Project {
  id: string;
  name: string;
  organization?: (string | null) | Organization;
  owner?: (string | null) | User;
  members?: (string | User)[] | null;
  workflow?: (string | null) | Workflow;
  stageId?: string | null;
  /**
   * UTC time in milliseconds since 1970-01-01
   */
  stageEnteredAt?: number | null;
  /**
   * UTC time in milliseconds since 1970-01-01
   */
  startAt?: number | null;
  /**
   * UTC time in milliseconds since 1970-01-01
   */
  targetEndAt?: number | null;
  description?: string | null;
  customData?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "workflows".
 */
export interface Workflow {
  id: string;
  recordType: 'organization' | 'project' | 'task';
  name: string;
  stages?:
    | {
        id?: string | null;
        name: string;
        category: 'backlog' | 'open' | 'active' | 'waiting' | 'done_success' | 'done_failure' | 'cancelled';
        color: 'gray' | 'blue' | 'green' | 'amber' | 'red' | 'violet' | 'teal' | 'pink';
        position: number;
        probability?: number | null;
      }[]
    | null;
  defaultStageId?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tasks".
 */
export interface Task {
  id: string;
  title: string;
  description?: string | null;
  project?: (string | null) | Project;
  relatedType?: ('organization' | 'project' | 'task') | null;
  relatedId?: string | null;
  parentTask?: (string | null) | Task;
  workflow?: (string | null) | Workflow;
  stageId?: string | null;
  /**
   * UTC time in milliseconds since 1970-01-01
   */
  stageEnteredAt?: number | null;
  rank?: string | null;
  priority: 'none' | 'low' | 'medium' | 'high' | 'urgent';
  assignees?: (string | User)[] | null;
  group?: (string | null) | Group;
  /**
   * UTC time in milliseconds since 1970-01-01
   */
  startAt?: number | null;
  /**
   * UTC time in milliseconds since 1970-01-01
   */
  dueAt?: number | null;
  /**
   * UTC time in milliseconds since 1970-01-01
   */
  completedAt?: number | null;
  customData?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "activity".
 */
export interface Activity {
  id: string;
  recordType: 'organization' | 'project' | 'task';
  recordId: string;
  verb:
    | 'record.created'
    | 'field.changed'
    | 'stage.changed'
    | 'assignment.changed'
    | 'comment.added'
    | 'mention.added'
    | 'attachment.added'
    | 'attachment.downloaded'
    | 'email.sent'
    | 'email.received'
    | 'relation.linked'
    | 'record.converted';
  actor?: (string | null) | User;
  data?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * UTC time in milliseconds since 1970-01-01
   */
  occurredAt: number;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "attachments".
 */
export interface Attachment {
  id: string;
  recordType: 'organization' | 'project' | 'task';
  recordId: string;
  fileName: string;
  sizeBytes: number;
  uploadedBy?: (string | null) | User;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "notifications".
 */
export interface Notification {
  id: string;
  user: string | User;
  type:
    | 'assigned'
    | 'mentioned'
    | 'due_soon'
    | 'overdue'
    | 'digest'
    | 'intake_received'
    | 'email_received'
    | 'invitation_accepted'
    | 'stalled';
  recordType?: ('organization' | 'project' | 'task') | null;
  recordId?: string | null;
  actor?: (string | null) | User;
  data?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  dedupeKey: string;
  /**
   * UTC time in milliseconds since 1970-01-01
   */
  readAt?: number | null;
  /**
   * UTC time in milliseconds since 1970-01-01
   */
  emailedAt?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "emailMessages".
 */
export interface EmailMessage {
  id: string;
  direction: 'outbound' | 'inbound';
  recordType?: ('organization' | 'project' | 'task') | null;
  recordId?: string | null;
  messageId: string;
  inReplyTo?: string | null;
  from: string;
  to?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  cc?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  subject?: string | null;
  textBody?: string | null;
  htmlFileKey?: string | null;
  attachments?: (string | Attachment)[] | null;
  status: 'queued' | 'sent' | 'failed' | 'received' | 'quarantined';
  error?: string | null;
  /**
   * UTC time in milliseconds since 1970-01-01
   */
  occurredAt: number;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "jobRuns".
 */
export interface JobRun {
  id: string;
  job: string;
  /**
   * UTC time in milliseconds since 1970-01-01
   */
  windowStart: number;
  status: 'running' | 'completed' | 'failed';
  processed?: number | null;
  created?: number | null;
  skipped?: number | null;
  durationMs?: number | null;
  cursor?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: string;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: string;
  document?:
    | ({
        relationTo: 'users';
        value: string | User;
      } | null)
    | ({
        relationTo: 'groups';
        value: string | Group;
      } | null)
    | ({
        relationTo: 'organizations';
        value: string | Organization;
      } | null)
    | ({
        relationTo: 'projects';
        value: string | Project;
      } | null)
    | ({
        relationTo: 'tasks';
        value: string | Task;
      } | null)
    | ({
        relationTo: 'workflows';
        value: string | Workflow;
      } | null)
    | ({
        relationTo: 'activity';
        value: string | Activity;
      } | null)
    | ({
        relationTo: 'attachments';
        value: string | Attachment;
      } | null)
    | ({
        relationTo: 'notifications';
        value: string | Notification;
      } | null)
    | ({
        relationTo: 'emailMessages';
        value: string | EmailMessage;
      } | null)
    | ({
        relationTo: 'jobRuns';
        value: string | JobRun;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: string;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: string;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  active?: T;
  groups?: T;
  reportsTo?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "groups_select".
 */
export interface GroupsSelect<T extends boolean = true> {
  name?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "organizations_select".
 */
export interface OrganizationsSelect<T extends boolean = true> {
  name?: T;
  website?: T;
  phone?: T;
  email?: T;
  owner?: T;
  customData?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects_select".
 */
export interface ProjectsSelect<T extends boolean = true> {
  name?: T;
  organization?: T;
  owner?: T;
  members?: T;
  workflow?: T;
  stageId?: T;
  stageEnteredAt?: T;
  startAt?: T;
  targetEndAt?: T;
  description?: T;
  customData?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tasks_select".
 */
export interface TasksSelect<T extends boolean = true> {
  title?: T;
  description?: T;
  project?: T;
  relatedType?: T;
  relatedId?: T;
  parentTask?: T;
  workflow?: T;
  stageId?: T;
  stageEnteredAt?: T;
  rank?: T;
  priority?: T;
  assignees?: T;
  group?: T;
  startAt?: T;
  dueAt?: T;
  completedAt?: T;
  customData?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "workflows_select".
 */
export interface WorkflowsSelect<T extends boolean = true> {
  recordType?: T;
  name?: T;
  stages?:
    | T
    | {
        id?: T;
        name?: T;
        category?: T;
        color?: T;
        position?: T;
        probability?: T;
      };
  defaultStageId?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "activity_select".
 */
export interface ActivitySelect<T extends boolean = true> {
  recordType?: T;
  recordId?: T;
  verb?: T;
  actor?: T;
  data?: T;
  occurredAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "attachments_select".
 */
export interface AttachmentsSelect<T extends boolean = true> {
  recordType?: T;
  recordId?: T;
  fileName?: T;
  sizeBytes?: T;
  uploadedBy?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "notifications_select".
 */
export interface NotificationsSelect<T extends boolean = true> {
  user?: T;
  type?: T;
  recordType?: T;
  recordId?: T;
  actor?: T;
  data?: T;
  dedupeKey?: T;
  readAt?: T;
  emailedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "emailMessages_select".
 */
export interface EmailMessagesSelect<T extends boolean = true> {
  direction?: T;
  recordType?: T;
  recordId?: T;
  messageId?: T;
  inReplyTo?: T;
  from?: T;
  to?: T;
  cc?: T;
  subject?: T;
  textBody?: T;
  htmlFileKey?: T;
  attachments?: T;
  status?: T;
  error?: T;
  occurredAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "jobRuns_select".
 */
export interface JobRunsSelect<T extends boolean = true> {
  job?: T;
  windowStart?: T;
  status?: T;
  processed?: T;
  created?: T;
  skipped?: T;
  durationMs?: T;
  cursor?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "settings".
 */
export interface Setting {
  id: string;
  appName?: string | null;
  timezone: string;
  locale: 'en' | 'es';
  currency: string;
  weekStartsOn: number;
  brand: {
    primaryHex?: string | null;
    radius: 'sm' | 'md' | 'lg';
  };
  modules?: {
    crm?: boolean | null;
    work?: boolean | null;
    intake?: boolean | null;
    mail?: boolean | null;
  };
  stalledDays: number;
  email: {
    fromName?: string | null;
    fromAddress?: string | null;
    senderStatus: 'unverified' | 'verified';
    inboundDomain?: string | null;
    inboundLocalPrefix?: string | null;
  };
  /**
   * UTC time in milliseconds since 1970-01-01
   */
  onboardedAt?: number | null;
  appliedTemplates?:
    | {
        key: string;
        version: number;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "settings_select".
 */
export interface SettingsSelect<T extends boolean = true> {
  appName?: T;
  timezone?: T;
  locale?: T;
  currency?: T;
  weekStartsOn?: T;
  brand?:
    | T
    | {
        primaryHex?: T;
        radius?: T;
      };
  modules?:
    | T
    | {
        crm?: T;
        work?: T;
        intake?: T;
        mail?: T;
      };
  stalledDays?: T;
  email?:
    | T
    | {
        fromName?: T;
        fromAddress?: T;
        senderStatus?: T;
        inboundDomain?: T;
        inboundLocalPrefix?: T;
      };
  onboardedAt?: T;
  appliedTemplates?:
    | T
    | {
        key?: T;
        version?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}