import { existsSync, mkdirSync, writeFileSync } from 'node:fs'
import { dirname, relative } from 'node:path'
import { extractSpecTable } from './lib/plan-rows.ts'
import { isMain, parseMilestoneCommand, paths, readText, REPO_ROOT, runCli } from './lib/repo.ts'
import { cell, parseTableDocument, renderTableDocument, type Table, type TableDocument } from './lib/table.ts'

const STATUS = 'Status'
const DEFAULT_STATUS = 'planned'
const CHANGES_HEADING = '## Changes from spec table'

export interface PlanResult {
  file: string
  content: string
  added: string[]
}

/** Adds a `Status` column after `Depends` (default `planned`) unless the table already has one. */
export function withStatusColumn(table: Table): Table {
  if (table.headers.includes(STATUS)) return table
  const dependsIndex = table.headers.indexOf('Depends')
  const at = dependsIndex < 0 ? table.headers.length : dependsIndex + 1
  const insert = (list: string[], value: string): string[] => [...list.slice(0, at), value, ...list.slice(at)]
  return { headers: insert(table.headers, STATUS), rows: table.rows.map((row) => insert(row, DEFAULT_STATUS)) }
}

/** Text of the "Changes from spec table" section (up to the next heading). */
export function changesSection(lines: string[]): string {
  const start = lines.findIndex((line) => line.trim() === CHANGES_HEADING)
  if (start < 0) return ''
  const end = lines.findIndex((line, i) => i > start && /^#{1,2}\s/.test(line))
  return lines.slice(start, end < 0 ? lines.length : end).join('\n')
}

function mentions(text: string, wp: string): boolean {
  return new RegExp(`(?<![\\w-])${wp}(?![\\w])`).test(text)
}

/**
 * Keeps every existing row, status and surrounding text; inserts spec rows that are missing, in spec order.
 * A missing row whose WP id is named in the changes section was removed deliberately and is not re-added.
 */
export function mergePlan(existing: TableDocument, spec: Table): { doc: TableDocument; added: string[] } {
  const table = withStatusColumn(existing.table)
  const rows = [...table.rows]
  const changes = changesSection(existing.after)
  const added: string[] = []
  let insertAt = 0
  for (const specRow of spec.rows) {
    const wp = cell(spec, specRow, 'WP')
    const found = rows.findIndex((row) => cell(table, row, 'WP') === wp)
    if (found >= 0) {
      insertAt = found + 1
    } else if (!mentions(changes, wp)) {
      rows.splice(
        insertAt,
        0,
        table.headers.map((h) => (h === STATUS ? DEFAULT_STATUS : cell(spec, specRow, h))),
      )
      insertAt += 1
      added.push(wp)
    }
  }
  return { doc: { ...existing, table: { headers: table.headers, rows } }, added }
}

function newPlanDocument(n: number, spec: Table): TableDocument {
  const m = String(n)
  return {
    before: [
      `# M${m} plan`,
      '',
      `Source: spec §21.3 M${m}. Generated by \`pnpm harness:plan m${m}\`; the lead adjusts rows to the repository state and records each change below with a one-line reason.`,
      '',
    ],
    table: withStatusColumn(spec),
    after: ['', CHANGES_HEADING, '- None.', ''],
  }
}

/** Builds the plan content for milestone `n` without writing it. */
export function buildPlan(opts: { root: string; n: number }): PlanResult {
  const spec = extractSpecTable(readText(paths.spec(opts.root)), opts.n)
  const file = paths.plan(opts.root, opts.n)
  if (!existsSync(file)) {
    const doc = newPlanDocument(opts.n, spec)
    return { file, content: renderTableDocument(doc), added: spec.rows.map((row) => cell(spec, row, 'WP')) }
  }
  const { doc, added } = mergePlan(parseTableDocument(readText(file)), spec)
  return { file, content: renderTableDocument(doc), added }
}

async function main(argv: string[]): Promise<number> {
  const { n, dryRun } = parseMilestoneCommand(argv)
  const result = buildPlan({ root: REPO_ROOT, n })
  if (dryRun) {
    process.stdout.write(result.content)
    return Promise.resolve(0)
  }
  mkdirSync(dirname(result.file), { recursive: true })
  writeFileSync(result.file, result.content)
  const addedText = result.added.length > 0 ? result.added.join(', ') : 'none'
  console.log(`wrote ${relative(REPO_ROOT, result.file)} (rows added: ${addedText})`)
  return Promise.resolve(0)
}

if (isMain(import.meta.url)) runCli(main)
