import type { DealSeed, LeadSeed } from './crm-types'

/** A small pipeline of fictional prospects so lead and deal screens and their tests have records at every stage. */
export const LEADS: readonly LeadSeed[] = [
  {
    key: 'optics-site',
    title: 'Online store for Northwind Optics',
    firstName: 'Priya',
    lastName: 'Shah',
    email: 'priya.shah@northwindoptics.example.test',
    phone: '+1 555-0101-01',
    companyName: 'Northwind Optics',
    organization: 'northwind-optics',
    source: 'Website form',
    owner: 'manager',
    assignees: [],
    stage: 'New',
    service: 'Website',
    budget: '$5k–20k',
  },
  {
    key: 'cpa-seo',
    title: 'Local SEO for Harbor CPA',
    firstName: 'Daniel',
    lastName: 'Okafor',
    email: 'daniel.okafor@harborcpa.example.test',
    phone: '+1 555-0101-02',
    companyName: 'Harbor CPA',
    organization: 'harbor-cpa',
    source: 'Referral',
    owner: 'staff1',
    assignees: [],
    stage: 'Contacted',
    service: 'SEO',
    budget: '$1k–5k',
  },
  {
    key: 'jewelers-social',
    title: 'Social media for Sterling Jewelers',
    firstName: 'Maria',
    lastName: 'Lopez',
    email: 'maria.lopez@sterlingjewelers.example.test',
    phone: '+1 555-0101-03',
    companyName: 'Sterling Jewelers',
    organization: 'sterling-jewelers',
    source: 'Social',
    owner: 'manager',
    assignees: [],
    stage: 'Qualified',
    service: 'Social media',
    budget: '$1k–5k',
  },
  {
    key: 'logistics-ads',
    title: 'Paid ads for Summit Logistics',
    firstName: 'Chen',
    lastName: 'Wei',
    email: 'chen.wei@summitlogistics.example.test',
    phone: '+1 555-0101-04',
    companyName: 'Summit Logistics',
    organization: 'summit-logistics',
    source: 'Ads',
    owner: 'staff1',
    assignees: [],
    stage: 'Disqualified',
    service: 'Ads',
    budget: 'Under $1k',
    lostReason: 'Budget',
    lostNote: 'Wanted a quote below the minimum engagement.',
  },
]

export const DEALS: readonly DealSeed[] = [
  {
    key: 'homes-rebrand',
    title: 'Rebrand for Keystone Homes',
    organization: 'keystone-homes',
    contacts: ['homes-owner'],
    primaryContact: 'homes-owner',
    valueAmountMinor: 1_800_000,
    expectedCloseDay: 21,
    stage: 'Discovery',
    owner: 'manager',
    assignees: [],
    serviceLines: ['Design'],
  },
  {
    key: 'solar-site',
    title: 'Website refresh for Evergreen Solar',
    organization: 'evergreen-solar',
    contacts: ['solar-marketing'],
    primaryContact: 'solar-marketing',
    valueAmountMinor: 2_400_000,
    expectedCloseDay: 30,
    stage: 'Proposal sent',
    owner: 'staff1',
    assignees: [],
    serviceLines: ['Website', 'SEO'],
  },
  {
    key: 'law-retainer',
    title: 'Monthly SEO retainer for Lakeside Law Office',
    organization: 'lakeside-law-office',
    contacts: ['law-partner'],
    primaryContact: 'law-partner',
    valueAmountMinor: 600_000,
    expectedCloseDay: -5,
    stage: 'Won',
    owner: 'manager',
    assignees: [],
    serviceLines: ['SEO'],
  },
  {
    key: 'kings-app',
    title: 'Booking app for Court Kings',
    organization: 'court-kings',
    contacts: ['kings-manager'],
    primaryContact: 'kings-manager',
    valueAmountMinor: 3_500_000,
    expectedCloseDay: -10,
    stage: 'Lost',
    owner: 'staff1',
    assignees: [],
    serviceLines: ['App development'],
    lostReason: 'Chose competitor',
    lostNote: 'Went with an in-house developer.',
  },
]
