import type { DealSeed, LeadSeed } from './crm-types'

const NORTHSTAR = 'northstar'
const HARBOR_PINE = 'harbor-pine'

export const LEADS: readonly LeadSeed[] = [
  {
    key: 'website-redesign',
    title: 'Website redesign inquiry',
    firstName: 'Avery',
    lastName: 'Chen',
    email: 'avery.chen@example.test',
    phone: '+1 212 555 0131',
    companyName: 'Example Organization',
    organization: 'example',
    source: 'Website form',
    owner: 'manager',
    assignees: ['staff1'],
    stage: 'New',
    service: 'Website',
    budget: '$5k–20k',
  },
  {
    key: 'seo-growth',
    title: 'SEO growth consultation',
    firstName: 'Marcus',
    lastName: 'Lee',
    email: 'marcus.lee@example.test',
    phone: '+1 415 555 0133',
    companyName: 'Northstar Health Studio',
    organization: NORTHSTAR,
    source: 'Referral',
    owner: 'manager',
    assignees: ['staff2'],
    stage: 'Contacted',
    service: 'SEO',
    budget: '$1k–5k',
  },
  {
    key: 'paid-social',
    title: 'Paid social launch',
    firstName: 'Jon',
    lastName: 'Bell',
    email: 'jon.bell@example.test',
    phone: '+1 617 555 0135',
    companyName: 'Harbor & Pine Retail',
    organization: HARBOR_PINE,
    source: 'Ads',
    owner: 'manager',
    assignees: ['staff2'],
    stage: 'Qualified',
    service: 'Ads',
    budget: '$5k–20k',
  },
  {
    key: 'client-portal',
    title: 'Client portal discovery',
    firstName: 'Elena',
    lastName: 'Torres',
    email: 'elena.torres@example.test',
    phone: '+1 415 555 0134',
    companyName: 'Northstar Health Studio',
    organization: NORTHSTAR,
    source: 'Email',
    owner: 'manager',
    assignees: ['staff1', 'staff2'],
    stage: 'Converted',
    service: 'App development',
    budget: '$20k+',
  },
  {
    key: 'brand-refresh',
    title: 'Brand refresh request',
    firstName: 'Sofia',
    lastName: 'Grant',
    email: 'sofia.grant@example.test',
    phone: '+1 617 555 0136',
    companyName: 'Harbor & Pine Retail',
    organization: HARBOR_PINE,
    source: 'Social',
    owner: 'manager',
    assignees: ['staff1'],
    stage: 'Disqualified',
    service: 'Design',
    budget: 'Under $1k',
    lostReason: 'Not a fit',
    lostNote: 'The requested scope is outside the current service mix.',
  },
]

export const DEALS: readonly DealSeed[] = [
  {
    key: 'website-engagement',
    title: 'Website redesign engagement',
    organization: 'example',
    contacts: ['avery', 'priya'],
    primaryContact: 'avery',
    valueAmountMinor: 1250000,
    expectedCloseDay: 14,
    stage: 'Discovery',
    owner: 'manager',
    assignees: ['staff1'],
    serviceLines: ['Website', 'Design'],
  },
  {
    key: 'seo-retainer',
    title: 'SEO growth retainer',
    organization: 'northstar',
    contacts: ['marcus'],
    primaryContact: 'marcus',
    valueAmountMinor: 480000,
    expectedCloseDay: 21,
    stage: 'Proposal sent',
    owner: 'manager',
    assignees: ['staff2'],
    serviceLines: ['SEO'],
  },
  {
    key: 'campaign-package',
    title: 'Spring campaign package',
    organization: HARBOR_PINE,
    contacts: ['jon'],
    primaryContact: 'jon',
    valueAmountMinor: 875000,
    expectedCloseDay: 30,
    stage: 'Negotiation',
    owner: 'manager',
    assignees: ['staff1', 'staff2'],
    serviceLines: ['Social media', 'Ads'],
  },
  {
    key: 'portal-build',
    title: 'Client portal build',
    organization: NORTHSTAR,
    contacts: ['elena', 'marcus'],
    primaryContact: 'elena',
    valueAmountMinor: 2400000,
    expectedCloseDay: -2,
    stage: 'Won',
    owner: 'manager',
    assignees: ['staff2'],
    serviceLines: ['App development'],
    sourceLead: 'client-portal',
  },
  {
    key: 'identity-project',
    title: 'Brand identity project',
    organization: HARBOR_PINE,
    contacts: ['sofia'],
    primaryContact: 'sofia',
    valueAmountMinor: 95000,
    expectedCloseDay: -5,
    stage: 'Lost',
    owner: 'manager',
    assignees: ['staff1'],
    serviceLines: ['Design'],
    lostReason: 'Budget',
    lostNote: 'The prospect deferred until the next planning cycle.',
  },
]
