import type { ProjectSeed } from './work-seed-types'

/** Planned local work for the ten client organizations supplied by the owner. */
export const PROJECTS: readonly ProjectSeed[] = [
  {
    name: 'Northwind Optics website plan',
    previousName: 'Northwind Optics delivery',
    organizationKey: 'northwind-optics',
    description: 'Proposed scope for review: service-page structure, appointment paths, and responsive quality checks.',
    stage: 'Planned',
    members: ['staff1'],
    startDay: 0,
    targetEndDay: 30,
  },
  {
    name: 'Harbor CPA website plan',
    previousName: 'Harbor Cpa delivery',
    organizationKey: 'harbor-cpa',
    description:
      'Proposed scope for review: accounting service pages, consultation paths, and bilingual navigation checks.',
    stage: 'Planned',
    members: ['staff1'],
    startDay: 0,
    targetEndDay: 30,
  },
  {
    name: 'Lakeside Law Office website plan',
    previousName: 'Lakeside Law Office delivery',
    organizationKey: 'lakeside-law-office',
    description: 'Proposed scope for review: practice-area navigation, mobile call paths, and intake-form checks.',
    stage: 'Planned',
    members: ['staff1'],
    startDay: 0,
    targetEndDay: 30,
  },
  {
    name: 'Lakeside Champion landing-page plan',
    previousName: 'Lakeside Champion delivery',
    organizationKey: 'lakeside-champion',
    description: 'Proposed scope for review: confirm the page brief, content hierarchy, and responsive layout.',
    stage: 'Planned',
    members: ['staff1'],
    startDay: 0,
    targetEndDay: 30,
  },
  {
    name: 'Sterling Jewelers storefront plan',
    previousName: 'Sterling Jewelers delivery',
    organizationKey: 'sterling-jewelers',
    description: 'Proposed scope for review: product-category navigation, storefront paths, and mobile quality checks.',
    stage: 'Planned',
    members: ['staff1'],
    startDay: 0,
    targetEndDay: 30,
  },
  {
    name: 'Summit Logistics website plan',
    previousName: 'Summit Logistics delivery',
    organizationKey: 'summit-logistics',
    description: 'Proposed scope for review: training catalogue, registration paths, and mobile checks.',
    stage: 'Planned',
    members: ['staff2'],
    startDay: 0,
    targetEndDay: 30,
  },
  {
    name: 'Keystone Homes website plan',
    previousName: 'Keystone Homes delivery',
    organizationKey: 'keystone-homes',
    description: 'Proposed scope for review: service-area content, seller inquiry paths, and mobile checks.',
    stage: 'Planned',
    members: ['staff2'],
    startDay: 0,
    targetEndDay: 30,
  },
  {
    name: 'Evergreen Solar website plan',
    previousName: 'Evergreen Solar delivery',
    organizationKey: 'evergreen-solar',
    description: 'Proposed scope for review: core content, partner paths, and responsive quality checks.',
    stage: 'Planned',
    members: ['staff2'],
    startDay: 0,
    targetEndDay: 30,
  },
  {
    name: 'Demo Agency website plan',
    previousName: 'Demo Agency delivery',
    organizationKey: 'demo-agency',
    description: 'Proposed scope for review: service pages, inquiry routing, and mobile performance checks.',
    stage: 'Planned',
    members: ['staff2'],
    startDay: 0,
    targetEndDay: 30,
  },
  {
    name: 'Court Kings website discovery',
    previousName: 'Court Kings delivery',
    organizationKey: 'court-kings',
    description: 'Proposed scope for review: confirm the brief, priority pages, and site structure before design.',
    stage: 'Planned',
    members: ['staff2'],
    startDay: 0,
    targetEndDay: 30,
  },
]
