import type { ProjectSeed } from './work-seed-types'

/** Planned local work for the ten client organizations supplied by the owner. */
export const PROJECTS: readonly ProjectSeed[] = [
  {
    name: 'Austin Optics website plan',
    previousName: 'Austin Optics delivery',
    organizationKey: 'austin-optics',
    description: 'Proposed scope for review: service-page structure, appointment paths, and responsive quality checks.',
    stage: 'Planned',
    members: ['staff1'],
    startDay: 0,
    targetEndDay: 30,
  },
  {
    name: 'ETCPA website plan',
    previousName: 'Etcpa delivery',
    organizationKey: 'etcpa',
    description:
      'Proposed scope for review: accounting service pages, consultation paths, and bilingual navigation checks.',
    stage: 'Planned',
    members: ['staff1'],
    startDay: 0,
    targetEndDay: 30,
  },
  {
    name: 'Shapiro Law Office website plan',
    previousName: 'Shapiro Law Office delivery',
    organizationKey: 'shapiro-law-office',
    description: 'Proposed scope for review: practice-area navigation, mobile call paths, and intake-form checks.',
    stage: 'Planned',
    members: ['staff1'],
    startDay: 0,
    targetEndDay: 30,
  },
  {
    name: 'Shapiro The Hero landing-page plan',
    previousName: 'Shapiro The Hero delivery',
    organizationKey: 'shapiro-the-hero',
    description: 'Proposed scope for review: confirm the page brief, content hierarchy, and responsive layout.',
    stage: 'Planned',
    members: ['staff1'],
    startDay: 0,
    targetEndDay: 30,
  },
  {
    name: 'AGR Gold storefront plan',
    previousName: 'Agr Gold delivery',
    organizationKey: 'agr-gold',
    description: 'Proposed scope for review: product-category navigation, storefront paths, and mobile quality checks.',
    stage: 'Planned',
    members: ['staff1'],
    startDay: 0,
    targetEndDay: 30,
  },
  {
    name: 'Fast Track website plan',
    previousName: 'Fast Track delivery',
    organizationKey: 'fast-track',
    description: 'Proposed scope for review: training catalogue, registration paths, and mobile checks.',
    stage: 'Planned',
    members: ['staff2'],
    startDay: 0,
    targetEndDay: 30,
  },
  {
    name: 'PBNJ website plan',
    previousName: 'Pbnj delivery',
    organizationKey: 'pbnj',
    description: 'Proposed scope for review: service-area content, seller inquiry paths, and mobile checks.',
    stage: 'Planned',
    members: ['staff2'],
    startDay: 0,
    targetEndDay: 30,
  },
  {
    name: 'Green Vision website plan',
    previousName: 'Green Vision delivery',
    organizationKey: 'green-vision',
    description: 'Proposed scope for review: core content, partner paths, and responsive quality checks.',
    stage: 'Planned',
    members: ['staff2'],
    startDay: 0,
    targetEndDay: 30,
  },
  {
    name: 'Mirch Media website plan',
    previousName: 'Mirch Media delivery',
    organizationKey: 'mirch-media',
    description: 'Proposed scope for review: service pages, inquiry routing, and mobile performance checks.',
    stage: 'Planned',
    members: ['staff2'],
    startDay: 0,
    targetEndDay: 30,
  },
  {
    name: 'Baller Squad website discovery',
    previousName: 'Baller Squad delivery',
    organizationKey: 'baller-squad',
    description: 'Proposed scope for review: confirm the brief, priority pages, and site structure before design.',
    stage: 'Planned',
    members: ['staff2'],
    startDay: 0,
    targetEndDay: 30,
  },
]
