import type { TaskSeed } from './work-seed-types'

const DESIGN = 'Design'
const DEVELOPMENT = 'Development'

export const SECOND_CLIENT_TASKS: readonly TaskSeed[] = [
  {
    title: 'Review training catalogue and registration',
    description: 'Review the training catalogue structure and map registration steps for client approval.',
    previousTitle: 'Kick off Fast Track delivery',
    stage: 'To do',
    priority: 'medium',
    assignees: ['staff1'],
    group: DESIGN,
    project: 'Fast Track website plan',
    startDay: 0,
    dueDay: 4,
  },
  {
    title: 'Check enrollment flow on mobile',
    description: 'Review the mobile enrollment path and record any technical questions before changes are proposed.',
    stage: 'To do',
    priority: 'medium',
    assignees: ['staff2'],
    group: DEVELOPMENT,
    project: 'Fast Track website plan',
    startDay: 0,
    dueDay: 7,
  },
  {
    title: 'Review service-area and seller content',
    description: 'Review service-area and seller content, then propose a page structure for client review.',
    previousTitle: 'Kick off Pbnj delivery',
    stage: 'To do',
    priority: 'medium',
    assignees: ['staff1'],
    group: DESIGN,
    project: 'PBNJ website plan',
    startDay: 0,
    dueDay: 4,
  },
  {
    title: 'Check mobile inquiry and call paths',
    description: 'Map mobile inquiry and call paths and identify details that need client confirmation.',
    stage: 'To do',
    priority: 'medium',
    assignees: ['staff2'],
    group: DEVELOPMENT,
    project: 'PBNJ website plan',
    startDay: 0,
    dueDay: 7,
  },
  {
    title: 'Review core and partner content',
    description: 'Review core and partner content and prepare a proposed information structure for approval.',
    previousTitle: 'Kick off Green Vision delivery',
    stage: 'To do',
    priority: 'medium',
    assignees: ['staff1'],
    group: DESIGN,
    project: 'Green Vision website plan',
    startDay: 0,
    dueDay: 4,
  },
  {
    title: 'Check partner inquiry flow',
    description: 'Map the partner inquiry path and list any integration questions for client review.',
    stage: 'To do',
    priority: 'medium',
    assignees: ['staff2'],
    group: DEVELOPMENT,
    project: 'Green Vision website plan',
    startDay: 0,
    dueDay: 7,
  },
  {
    title: 'Review agency service pages',
    description: 'Review agency service pages and prepare a proposed content hierarchy for approval.',
    previousTitle: 'Kick off Mirch Media delivery',
    stage: 'To do',
    priority: 'medium',
    assignees: ['staff1'],
    group: DESIGN,
    project: 'Mirch Media website plan',
    startDay: 0,
    dueDay: 4,
  },
  {
    title: 'Check mobile performance and contact routing',
    description: 'Review mobile performance paths and contact routing, then document proposed follow-up work.',
    stage: 'To do',
    priority: 'medium',
    assignees: ['staff2'],
    group: DEVELOPMENT,
    project: 'Mirch Media website plan',
    startDay: 0,
    dueDay: 7,
  },
  {
    title: 'Confirm project brief and priority pages',
    description: 'Confirm the project brief and priority pages with the client before preparing a design direction.',
    previousTitle: 'Kick off Baller Squad delivery',
    stage: 'To do',
    priority: 'medium',
    assignees: ['staff1'],
    group: DESIGN,
    project: 'Baller Squad website discovery',
    startDay: 0,
    dueDay: 4,
  },
  {
    title: 'Draft navigation and content structure',
    description: 'Draft a navigation and content outline after the brief and priority pages are confirmed.',
    stage: 'To do',
    priority: 'medium',
    assignees: ['staff2'],
    group: DEVELOPMENT,
    project: 'Baller Squad website discovery',
    startDay: 0,
    dueDay: 7,
  },
]
