import type { TaskSeed } from './work-seed-types'

const DESIGN = 'Design'
const DEVELOPMENT = 'Development'

export const FIRST_CLIENT_TASKS: readonly TaskSeed[] = [
  {
    title: 'Review service-page hierarchy',
    description: 'Review the existing service pages and draft a proposed hierarchy for client review.',
    previousTitle: 'Kick off Austin Optics delivery',
    stage: 'To do',
    priority: 'medium',
    assignees: ['staff1'],
    group: DESIGN,
    project: 'Austin Optics website plan',
    startDay: 0,
    dueDay: 4,
  },
  {
    title: 'Check appointment and contact paths',
    description: 'Map the current appointment and contact paths, then list any changes for approval.',
    stage: 'To do',
    priority: 'medium',
    assignees: ['staff2'],
    group: DEVELOPMENT,
    project: 'Austin Optics website plan',
    startDay: 0,
    dueDay: 7,
  },
  {
    title: 'Review accounting service pages',
    description: 'Review the accounting service pages and note any content or navigation questions for client review.',
    previousTitle: 'Kick off Etcpa delivery',
    stage: 'To do',
    priority: 'medium',
    assignees: ['staff1'],
    group: DESIGN,
    project: 'ETCPA website plan',
    startDay: 0,
    dueDay: 4,
  },
  {
    title: 'Check consultation form and navigation',
    description: 'Map the consultation form path and review navigation behavior before implementation.',
    stage: 'To do',
    priority: 'medium',
    assignees: ['staff2'],
    group: DEVELOPMENT,
    project: 'ETCPA website plan',
    startDay: 0,
    dueDay: 7,
  },
  {
    title: 'Review practice-area navigation',
    description: 'Review the practice-area structure and prepare a proposed navigation for client review.',
    previousTitle: 'Kick off Shapiro Law Office delivery',
    stage: 'To do',
    priority: 'medium',
    assignees: ['staff1'],
    group: DESIGN,
    project: 'Shapiro Law Office website plan',
    startDay: 0,
    dueDay: 4,
  },
  {
    title: 'Check mobile call and intake paths',
    description: 'Check the mobile call and intake paths and list any behavior that needs client approval.',
    stage: 'To do',
    priority: 'medium',
    assignees: ['staff2'],
    group: DEVELOPMENT,
    project: 'Shapiro Law Office website plan',
    startDay: 0,
    dueDay: 7,
  },
  {
    title: 'Confirm landing-page brief',
    description: 'Review the landing-page brief, identify missing inputs, and confirm priorities with the client.',
    previousTitle: 'Kick off Shapiro The Hero delivery',
    stage: 'To do',
    priority: 'medium',
    assignees: ['staff1'],
    group: DESIGN,
    project: 'Shapiro The Hero landing-page plan',
    startDay: 0,
    dueDay: 4,
  },
  {
    title: 'Prepare responsive page structure',
    description: 'Draft a responsive page outline from the approved brief before implementation begins.',
    stage: 'To do',
    priority: 'medium',
    assignees: ['staff2'],
    group: DEVELOPMENT,
    project: 'Shapiro The Hero landing-page plan',
    startDay: 0,
    dueDay: 7,
  },
  {
    title: 'Review product-category navigation',
    description: 'Review product categories and prepare a proposed storefront navigation for approval.',
    previousTitle: 'Kick off Agr Gold delivery',
    stage: 'To do',
    priority: 'medium',
    assignees: ['staff1'],
    group: DESIGN,
    project: 'AGR Gold storefront plan',
    startDay: 0,
    dueDay: 4,
  },
  {
    title: 'Check storefront mobile flow',
    description: 'Map the mobile storefront path from category browsing to product details and note open questions.',
    stage: 'To do',
    priority: 'medium',
    assignees: ['staff2'],
    group: DEVELOPMENT,
    project: 'AGR Gold storefront plan',
    startDay: 0,
    dueDay: 7,
  },
]
