/** First and last names used to make contacts and leads; mixed on purpose. */
export const FIRST_NAMES = [
  'Olivia',
  'Liam',
  'Noah',
  'Emma',
  'Ava',
  'Sophia',
  'Mason',
  'Isabella',
  'Amelia',
  'Lucas',
  'Mia',
  'Ethan',
  'Harper',
  'Elijah',
  'Evelyn',
  'Aarav',
  'Priya',
  'Rohan',
  'Ananya',
  'Vikram',
  'Meera',
  'Arjun',
  'Isha',
  'Kabir',
  'Diya',
  'Carlos',
  'Lucia',
  'Mateo',
  'Valentina',
  'Andre',
  'Fatima',
  'Omar',
  'Layla',
  'Yusuf',
  'Mei',
  'Hiro',
  'Sakura',
  'Jin',
  'Nia',
  'Kwame',
  'Zainab',
  'Tariq',
  'Elena',
  'Nikolai',
  'Ingrid',
  'Lars',
  'Chloe',
  'Hugo',
  'Grace',
  'Felix',
] as const

export const LAST_NAMES = [
  'Anderson',
  'Bennett',
  'Carter',
  'Dawson',
  'Ellis',
  'Foster',
  'Graham',
  'Hughes',
  'Irving',
  'Jensen',
  'Kapoor',
  'Mehta',
  'Sharma',
  'Iyer',
  'Reddy',
  'Nair',
  'Gupta',
  'Banerjee',
  'Chopra',
  'Desai',
  'Alvarez',
  'Bianchi',
  'Castillo',
  'Dubois',
  'Esposito',
  'Fischer',
  'Garcia',
  'Haddad',
  'Ivanov',
  'Jansen',
  'Khan',
  'Lindqvist',
  'Moreau',
  'Nakamura',
  'Okafor',
  'Petrov',
  'Quinn',
  'Rossi',
  'Schmidt',
  'Tanaka',
  'Underwood',
  'Vasquez',
  'Whitfield',
  'Xu',
  'Yamada',
  'Zhang',
  'Abbott',
  'Brooks',
  'Coleman',
  'Dalton',
] as const

/** Extra team members the demo adds on top of the four base users. */
export interface DemoTeamMember {
  readonly key: string
  readonly name: string
  readonly email: string
  readonly group: 'Design' | 'Development' | null
}

export const TEAM: readonly DemoTeamMember[] = [
  { key: 'priya', name: 'Priya Nair', email: 'priya.nair@demo.example.test', group: null },
  { key: 'marcus', name: 'Marcus Lee', email: 'marcus.lee@demo.example.test', group: null },
  { key: 'sofia', name: 'Sofia Rossi', email: 'sofia.rossi@demo.example.test', group: 'Design' },
  { key: 'kenji', name: 'Kenji Watanabe', email: 'kenji.watanabe@demo.example.test', group: 'Development' },
  { key: 'amara', name: 'Amara Okafor', email: 'amara.okafor@demo.example.test', group: 'Design' },
  { key: 'diego', name: 'Diego Alvarez', email: 'diego.alvarez@demo.example.test', group: 'Development' },
]

/** Team keys that work leads and deals. */
export const SALES_KEYS = ['owner', 'manager', 'priya', 'marcus'] as const
/** Team keys that deliver projects and tasks. */
export const DELIVERY_KEYS = ['staff1', 'staff2', 'sofia', 'kenji', 'amara', 'diego'] as const
