import { readdirSync, readFileSync, writeFileSync } from 'node:fs'
import { join } from 'node:path'
import { parseJsonc } from './lib/jsonc'
import { isMain } from './lib/report'
import { isPlatformHosted, parseTenant, tenantEnvKey, type Tenant } from './lib/tenant-schema'

type Config = Record<string, unknown>

interface BindingInput {
  readonly worker: string
  readonly d1: Config
  readonly bucket: string
  readonly intakeNamespace: string
  readonly authNamespace: string
  // Remote only takes effect when a lead run enables remote bindings (E-006); deploys ignore it.
  readonly remote: boolean
}

const OUTPUT = 'apps/web/wrangler.jsonc'
const MAIL_ROUTER_OUTPUT = 'apps/mail-router/wrangler.jsonc'
const CRON_EVERY_15_MINUTES = '*/15 * * * *'
const LOCAL_D1_ID = '00000000-0000-0000-0000-000000000000'
const HEADER = [
  '// Generated by scripts/gen-wrangler.ts from tenants/*.jsonc (spec §19.2). Do not edit; run `pnpm gen:wrangler`.',
  '// The top level is local development only and has no remote bindings, so builds never contact Cloudflare (E-006).',
].join('\n')

/** Bindings every Worker has, with identical names so application code never branches on the tenant. */
function bindings(input: BindingInput): Config {
  return {
    d1_databases: [{ binding: 'D1', ...input.d1, ...(input.remote ? { remote: true } : {}) }],
    r2_buckets: [{ binding: 'R2', bucket_name: input.bucket, ...(input.remote ? { remote: true } : {}) }],
    send_email: [{ name: 'EMAIL' }],
    services: [{ binding: 'WORKER_SELF_REFERENCE', service: input.worker }],
    ratelimits: [
      { name: 'RATE_LIMIT_INTAKE', namespace_id: input.intakeNamespace, simple: { limit: 10, period: 60 } },
      { name: 'RATE_LIMIT_AUTH', namespace_id: input.authNamespace, simple: { limit: 20, period: 60 } },
    ],
  }
}

/** Top level of the generated file: the local development Worker, never a tenant. */
export function baseConfig(): Config {
  const d1 = { database_name: 'ops-dev', database_id: LOCAL_D1_ID }
  return {
    $schema: 'node_modules/wrangler/config-schema.json',
    name: 'ops-dev',
    main: 'worker.ts',
    compatibility_date: '2025-08-15',
    compatibility_flags: ['nodejs_compat', 'global_fetch_strictly_public'],
    assets: { directory: '.open-next/assets', binding: 'ASSETS' },
    observability: { enabled: true },
    ...bindings({ worker: 'ops-dev', d1, bucket: 'ops-dev', intakeNamespace: '1', authNamespace: '2', remote: false }),
  }
}

function routing(tenant: Tenant): Config {
  if (tenant.hostType === 'workers_dev') return { workers_dev: true }
  return { workers_dev: false, routes: [{ pattern: tenant.host, custom_domain: true }] }
}

function vars(tenant: Tenant): Record<string, string> {
  const origin = tenant.host === undefined ? {} : { APP_ORIGIN: `https://${tenant.host}` }
  return {
    TENANT_SLUG: tenant.slug,
    TENANT_DISPLAY_NAME: tenant.displayName,
    ...origin,
    INBOUND_DOMAIN: tenant.email.inboundDomain,
    TURNSTILE_HOSTNAMES: tenant.intake.turnstileHostnames.join(','),
    MAIL_TRANSPORT: tenant.email.enabled ? 'cloudflare' : 'disabled',
    MAIL_FROM_ADDRESS: tenant.email.fromAddress,
    MAIL_FROM_NAME: tenant.email.fromName,
  }
}

/** Environment `env.<slug>`, holding only this tenant's own database, bucket and rate-limit namespaces (spec §19.5). */
export function tenantEnv(tenant: Tenant): Config {
  const worker = `ops-${tenant.slug}`
  const d1 = { database_name: tenant.d1.name, ...(tenant.d1.id === undefined ? {} : { database_id: tenant.d1.id }) }
  const { intake, auth } = tenant.rateLimitNamespaces
  return {
    name: worker,
    ...routing(tenant),
    ...bindings({ worker, d1, bucket: tenant.r2.bucket, intakeNamespace: intake, authNamespace: auth, remote: true }),
    vars: vars(tenant),
    triggers: { crons: [CRON_EVERY_15_MINUTES] },
  }
}

/** Throws when two tenants share a slug, database, bucket or rate-limit namespace. */
export function assertIsolated(tenants: readonly Tenant[]): void {
  const owned = tenants.flatMap((tenant) => [
    tenant.slug,
    `d1:${tenant.d1.name}`,
    `r2:${tenant.r2.bucket}`,
    `ratelimit:${tenant.rateLimitNamespaces.intake}`,
    `ratelimit:${tenant.rateLimitNamespaces.auth}`,
  ])
  const shared = new Set(owned.filter((value, index) => owned.indexOf(value) !== index))
  if (shared.size > 0) throw new Error(`tenants share resources: ${[...shared].join(', ')}`)

  const platformInboundDomains = tenants.filter(isPlatformHosted).map((tenant) => tenant.email.inboundDomain)
  const distinctInboundDomains = new Set(platformInboundDomains)
  if (distinctInboundDomains.size > 1) {
    throw new Error(`platform tenants must share one inbound domain: ${[...distinctInboundDomains].join(', ')}`)
  }
}

/** Reads and validates every `tenants/*.jsonc` below `root`, ordered by `deployOrder`. */
export function loadTenants(root: string): Tenant[] {
  const dir = join(root, 'tenants')
  const files = readdirSync(dir).filter((file) => file.endsWith('.jsonc'))
  const tenants = files.map((file) => parseTenant(parseJsonc(readFileSync(join(dir, file), 'utf8')), `tenants/${file}`))
  return tenants.sort((a, b) => a.deployOrder - b.deployOrder)
}

/** Renders the complete `apps/web/wrangler.jsonc` for `tenants`. */
export function renderWranglerConfig(tenants: readonly Tenant[]): string {
  assertIsolated(tenants)
  const env = Object.fromEntries(tenants.map((tenant) => [tenant.slug, tenantEnv(tenant)]))
  return `${HEADER}\n${JSON.stringify({ ...baseConfig(), env }, null, 2)}\n`
}

/** Renders the shared mail router with one service binding for each platform-hosted tenant. */
export function renderMailRouterConfig(tenants: readonly Tenant[]): string {
  assertIsolated(tenants)
  const platformTenants = tenants.filter(isPlatformHosted)
  const inboundDomain = platformTenants[0]?.email.inboundDomain
  const config: Config = {
    $schema: 'node_modules/wrangler/config-schema.json',
    name: 'ops-mail-router',
    main: 'src/index.ts',
    compatibility_date: '2025-08-15',
    compatibility_flags: ['nodejs_compat', 'global_fetch_strictly_public'],
    observability: { enabled: true },
    ...(inboundDomain === undefined ? {} : { routes: [{ pattern: inboundDomain, custom_domain: true }] }),
    services: platformTenants.map((tenant) => ({
      binding: tenantEnvKey('TENANT', tenant.slug),
      service: `ops-${tenant.slug}`,
    })),
    vars: { PLATFORM_DOMAIN: inboundDomain?.startsWith('in.') ? inboundDomain.slice(3) : (inboundDomain ?? '') },
  }
  return `${HEADER}\n${JSON.stringify(config, null, 2)}\n`
}

if (isMain(import.meta.url)) {
  const root = process.cwd()
  const tenants = loadTenants(root)
  writeFileSync(join(root, OUTPUT), renderWranglerConfig(tenants))
  writeFileSync(join(root, MAIL_ROUTER_OUTPUT), renderMailRouterConfig(tenants))
  console.log(`gen-wrangler: wrote ${OUTPUT}`)
  console.log(`gen-wrangler: wrote ${MAIL_ROUTER_OUTPUT}`)
}
