import {
  convertLeadSchema,
  createContactSchema,
  createDealSchema,
  createLeadSchema,
  createOrganizationSchema,
  markLostSchema,
  moveDealSchema,
  moveLeadSchema,
  setCustomFieldsSchema,
  updateContactSchema,
  updateDealSchema,
  updateLeadSchema,
  updateOrganizationSchema,
} from '@ops/module-crm'
import type { ApiContract } from './contract-types'

/** CRM record endpoints (spec §12): organizations, contacts, leads and deals. */
export const CRM_CONTRACTS = {
  'leads.list': {
    method: 'GET',
    path: '/api/v1/leads',
    summary: 'Leads you can see, newest first; ?page=&limit= (max 100).',
    success: 200,
  },
  'leads.get': { method: 'GET', path: '/api/v1/leads/:id', summary: 'One lead.', success: 200 },
  'leads.create': {
    method: 'POST',
    path: '/api/v1/leads',
    summary: 'Create a lead.',
    body: createLeadSchema,
    success: 201,
  },
  'leads.update': {
    method: 'PATCH',
    path: '/api/v1/leads/:id',
    summary: 'Change lead fields while it is still at expectedUpdatedAt.',
    body: updateLeadSchema.omit({ id: true }),
    success: 200,
  },
  'leads.move': {
    method: 'POST',
    path: '/api/v1/leads/:id/move',
    summary: 'Move a lead to another stage; stage requirements and the lost-reason rule apply.',
    body: moveLeadSchema.omit({ leadId: true }),
    success: 200,
  },
  'leads.lost': {
    method: 'POST',
    path: '/api/v1/leads/:id/lost',
    summary: 'Mark a lead lost with a lost reason.',
    body: markLostSchema.omit({ id: true }),
    success: 200,
  },
  'leads.convert': {
    method: 'POST',
    path: '/api/v1/leads/:id/convert',
    summary: 'Convert a lead into a deal, creating or linking its organization and contact.',
    body: convertLeadSchema.omit({ leadId: true }),
    success: 200,
  },
  'deals.list': {
    method: 'GET',
    path: '/api/v1/deals',
    summary: 'Deals you can see, newest first; ?page=&limit= (max 100).',
    success: 200,
  },
  'deals.get': { method: 'GET', path: '/api/v1/deals/:id', summary: 'One deal.', success: 200 },
  'deals.create': {
    method: 'POST',
    path: '/api/v1/deals',
    summary: 'Create a deal.',
    body: createDealSchema,
    success: 201,
  },
  'deals.update': {
    method: 'PATCH',
    path: '/api/v1/deals/:id',
    summary: 'Change deal fields while it is still at expectedUpdatedAt.',
    body: updateDealSchema.omit({ id: true }),
    success: 200,
  },
  'deals.move': {
    method: 'POST',
    path: '/api/v1/deals/:id/move',
    summary: 'Move a deal to another stage; stage requirements and the lost-reason rule apply.',
    body: moveDealSchema.omit({ dealId: true }),
    success: 200,
  },
  'deals.lost': {
    method: 'POST',
    path: '/api/v1/deals/:id/lost',
    summary: 'Mark a deal lost with a lost reason.',
    body: markLostSchema.omit({ id: true }),
    success: 200,
  },
  'organizations.list': {
    method: 'GET',
    path: '/api/v1/organizations',
    summary: 'Organizations you can see, newest first; ?page=&limit= (max 100).',
    success: 200,
  },
  'organizations.get': { method: 'GET', path: '/api/v1/organizations/:id', summary: 'One organization.', success: 200 },
  'organizations.create': {
    method: 'POST',
    path: '/api/v1/organizations',
    summary: 'Create a organization.',
    body: createOrganizationSchema,
    success: 201,
  },
  'organizations.update': {
    method: 'PATCH',
    path: '/api/v1/organizations/:id',
    summary: 'Change organization fields while it is still at expectedUpdatedAt.',
    body: updateOrganizationSchema.omit({ id: true }),
    success: 200,
  },
  'contacts.list': {
    method: 'GET',
    path: '/api/v1/contacts',
    summary: 'Contacts you can see, newest first; ?page=&limit= (max 100).',
    success: 200,
  },
  'contacts.get': { method: 'GET', path: '/api/v1/contacts/:id', summary: 'One contact.', success: 200 },
  'contacts.create': {
    method: 'POST',
    path: '/api/v1/contacts',
    summary: 'Create a contact.',
    body: createContactSchema,
    success: 201,
  },
  'contacts.update': {
    method: 'PATCH',
    path: '/api/v1/contacts/:id',
    summary: 'Change contact fields while it is still at expectedUpdatedAt.',
    body: updateContactSchema.omit({ id: true }),
    success: 200,
  },
  'records.customFields': {
    method: 'PATCH',
    path: '/api/v1/records/:type/:id/custom-fields',
    summary:
      'Set tenant-defined field values on an organization, contact, lead or deal while it is at expectedUpdatedAt. Empty clears a field; each invalid key is named.',
    body: setCustomFieldsSchema.omit({ type: true, id: true }),
    success: 200,
  },
} as const satisfies Readonly<Record<string, ApiContract>>
